### ISSUE TITLE
Export rules as JSON, there is no RuleHolder

### ISSUE THREAD

**Issue by UlasSAYGINIM** [AgentCosmic/xvalid#2]
I couldnt find the way to run Export rules as JSON example.
can you explain it too?
because it seems ruleholder object not created too. did you forget to commit these functions also?

can you look at it? and thank you for fast response for previous issue.

**Comment by AgentCosmic** [comment]
There's no function to export as JSON because the format is up to you to decide. In the README, you can see a sample code for how I did it. Basically I put all the models/validators in a map and serializes it into JSON, where the top level key is the model name.

**Comment by UlasSAYGINIM** [comment]
thank you for information. can you share your example? it can be good for beginners for golang.

**Comment by AgentCosmic** [comment]
Copied from the second example in README:

```go
func createValidationMap(model ...ruleHolder) map[string]interface{} {
	rules := make(map[string]interface{})
	for _, m := range model {
		rules[reflect.ValueOf(m).Type().Name()] = mapRules(m)
	}
	return rules
}

func mapRules(model ruleHolder) map[string][]interface{} {
	validators := model.ValidationRules().Validators()
	rmap := make(map[string][]interface{})
	for _, v := range validators {
		if !v.HTMLCompatible() {
			continue
		}
		name := v.Name()
		rules, ok := rmap[name]
		if !ok {
			rules = make([]interface{}, 0)
		}
		rules = append(rules, v)
		rmap[name] = rules
	}
	return rmap
}


func main() {
	rules := createValidationMap(model.Member{}, model.Store{}, model.Product{})
	b, err := json.MarshalIndent(rules, "", "	")
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}
```

In this line there are some example models I'm using. Gotta replace it with your own:

```go
rules := createValidationMap(model.Member{}, model.Store{}, model.Product{})
```

**Comment by UlasSAYGINIM** [comment]
can you share example models and ruleHolder object definition?

**Comment by AgentCosmic** [comment]
It's also in the README, first sample:

```go
// Store model
type Store struct {
	Name          string     `json:"name"`
	Address       string     `json:"address"`
	Description   string     `json:"description"`
	Tax           int        `json:"tax"`
}

// ValidationRules for this model.
func (store Store) ValidationRules() xvalid.Rules {
	return xvalid.New(&store).
		Field(&store.Name, xvalid.MinStr(4).Optional().SetMessage("Please lengthen name to 4 characters or more"),
			xvalid.MaxStr(80).SetMessage("Please shorten name to 80 characters or less"),
			xvalid.Pattern("^[a-zA-Z0-9_]+$").Optional().SetMessage("Name may contain alphabets, numbers and underscores"),
			xvalid.Pattern("[a-zA-Z]").Optional().SetMessage("Name must contain at least 1 alphabet"),
			xvalid.FieldFunc(func(fieldName string, value interface{}) xvalid.Error {
				name := value.(string)
				if name == "" {
					return nil
				}
				if name == "admin" {
					return xvalid.NewError("This name is not allowed", fieldName)
				}
				return nil
			})).
		Field(&store.Address, xvalid.Required(), xvalid.MaxStr(120)).
		Field(&store.Description, xvalid.MaxStr(1500)).
		Field(&store.Tax, xvalid.MinInt(0), xvalid.MaxInt(100))
}

// Validate the model and return errors if validation fails.
func (store Store) Validate() error {
	return store.ValidationRules().Validate(store)
}

// then validate
store := Store{}
err := store.Validate()
if err != nil {
	panic(err)
}
```

**Comment by UlasSAYGINIM** [comment]
firstly , thank you fo helping me but i couldnt see definition of ruleHolder, when i try to run second example from readme it gives error about there is no ruleholder. i dont know how to define ruleholder. i couldnt understand what to do?
can you define rule holder? because i cant run second example. i didnt understand the second example from readme.
i can run first one without problem.  i coulndt have success for second one. i am not so good at golang.

**Comment by AgentCosmic** [comment]
When you call `createValidationMap()`, make sure to pass in a valid model with validation rules. The example I gave don't have real models. I think that's why you're getting that error.

**Comment by UlasSAYGINIM** [comment]
this is why i am asking. i couldnt understand how to do. maybe later i will look it.
