### ISSUE TITLE
Question about string length validation

### ISSUE THREAD

**Issue by pacifico** [AgentCosmic/xvalid#3]
I was browsing your code as I am contemplating replacing use of [ozzo-validation](https://github.com/go-ozzo/ozzo-validation) with something that is better able to provide a structured error report in a project I am currently working on.

I noticed use of `len(str)` in lines 113 and 168 of [validators.go](https://github.com/AgentCosmic/xvalid/blob/master/validators.go).

Would you prefer to use `len([]rune(string))`, as `len(str)` returns the number of bytes in a string, not the number of characters? (as posed in [this SO question](https://stackoverflow.com/questions/12668681/how-to-get-the-number-of-characters-in-a-string))

**Comment by AgentCosmic** [comment]
Fixed with lastest release.
